### PR TITLE
Use setuptools and add travisCI and Coveralls.io

### PR DESCRIPTION
**Pull request by Toilal**
Currently there's no test in this project, but is here the structure with setuptools and travisCI configuration.

### CODE REVIEW

**Comment by Toilal** [comment]
`antfs-cli` module should be renamed => `antfs_cli`, or maybe even simpler `antfs`. see https://travis-ci.org/Tigge/Garmin-Forerunner-610-Extractor/jobs/45695612

As `antfs` is already registered on pypi, i would suggest `antfs-cli` as pypi package name and repository name and `antfs_cli`as  module name (antfs_cli.py filename). Are you ok ?

**Comment by Tigge** [comment]
Had a bit of power outage here. Yeah, `antfs_cli` is fine by me.

**Comment by Tigge** [comment]
Should this still fail now?

**Comment by Toilal** [comment]
I'll run it again, it should work now.

**Comment by Toilal** [comment]
Well i can't run it because i don't have access to the repository, you can restart the run in travisCI page. Click on the Details link on the right just Here, and then restart the build.

**Comment by Toilal** [comment]
I'll rebase on master, and it will relaunch build on travisCI

**Comment by Tigge** [comment]
I restarted the build but it still seems to fail to find the openant library.

**Comment by Tigge** [comment]
Eventually openant should be published to PyPi, but for now it should be possible for TravisCI to fetch it directly from the git repository, right?

**Comment by Tigge** [comment]
Adding `-e git+https://github.com/Tigge/openant.git#egg=openant` in requirements.txt perhaps?

**Comment by Toilal** [comment]
That's what i tried to do in `travis.yml`, but seems it doesn't work, i'll modify requirements.txt to try.

**Comment by Tigge** [comment]
Nice!

**Comment by Toilal** [comment]
I can rebase in a single commit if you want ?

**Comment by Tigge** [comment]
Yes, please do-

**Comment by Tigge** [comment]
Thanks!

**Pull request merged**
