### PR TITLE
Add progress callback on the start of the upload (#86)

### PR DESCRIPTION
**Pull request by mgr01**
Handles `callback(0)` made after the upload request was successfully created.

Tested with `master` and `progress-bar` (Tigge/openant#5) branches of openant.

Should be merged before the Tigge/openant#5.

### CODE REVIEW

**Comment by Tigge** [comment]
Looks good! It needs to be rebased now with the python 3 work though, do you mind, or should I?

**Comment by mgr01** [comment]
I'll do it.

**Comment by mgr01** [comment]
done

**Comment by Tigge** [comment]
Thanks!

**Pull request merged**
